### ISSUE TITLE
player stuck buffering

### ISSUE THREAD

**Issue by YuryDmitrienko** [nuhkoca/DaggerExoPlayer#1]
Hi. I just explore your article and project. And i found issue that is exoplayer stuck buffering after pause/resume application. Can you check it please?

**Comment by nuhkoca** [comment]
Hi @YuryDmitrienko,

Thanks for reporting! I will deal with it asap!

**Comment by nuhkoca** [comment]
Hi @YuryDmitrienko 

I fixed the issue by the last commit. Can you please check and let me know? Thanks for reporting.
